
method: 'CNN'
model: 'CNN'
batch_size: 100
seed: 42
learning_rate: 0.001
max_length: 100
max_distance: 60
pos_embedding_dim: 5
conv_filters: 100
dense_units: 200
dropout: 0.5
epochs: 200
patience: 200
label_smoothing: 0