

seed: 1234

pre_trained_path: 'glove_100'

embed_dim: 100
hidden_dim: 100
num_layers: 1

max_length: 100

embed_dropout: 0.3
lstm_dropout: 0.3
linear_dropout: 0.5

epochs: 30

batch_size: 10

learning_rate: 1.0
l2_decay: 0.00001

gradient_clip: 5
clip_norm: False