
method: 'CNN'
model: 'CNN'
batch_size: 100
seed: 1234
learning_rate: 0.0001
max_length: 100
max_distance: 60
pos_embedding_dim: 5
conv_filters: 100
dense_units: 200
dropout: 0.3
epochs: 400
patience: 30
label_smoothing: 0