
pre_trained_name: 'glove_300_2'
max_sentence_length: 90

hidden_size: 300
pos_embed_dim: 50
attention_size: 50

latent_types: 3

word_dropout: 0.7
lstm_dropout: 0.7
z_dropout: 0.5

num_heads: 4

seed: 42

epochs: 100
label_smoothing: 0.3
batch_size: 20
patience: 200

learning_rate: 1
lr_decay: 0.6
optimizer: 'adadelta'
l2_coef: 0.00001

gradient_clip: 1