

seed: 42

epochs: 5

max_length: 128

batch_size: 16

learning_rate: 0.00002
learning_rate_BERT: 0.00002

weight_decay: 0

gradient_accumulation_steps: 1
warmup_proportion: 0.1

dropout: 0.1

gradient_clip: 1